describe('register user', () => {
  beforeEach(() => {
    cy.visit('https://automationexercise.com/')
  })
  it('Sign Up', () => {
    cy.url().should('eq', 'https://automationexercise.com/')
    cy.log('Step 1: Click on "Sign up/ Login" button')
      cy.contains('a', 'Signup / Login').click()
    cy.log('Step 2: Verify "New User SignUp!" is visible')
      cy.contains('h2','New User Signup!')
    cy.log('Step 3: Enter name and email address')
      cy.get('[data-qa="signup-name"]').type('testname')
      cy.get('[data-qa="signup-email"]').type('testname1@outlook.com')
      cy.log('Step 4: Click "Signup" button')
      cy.get('[data-qa="signup-button"]').click()
    cy.log('Step 5: Verify that "ENTER ACCOUNT INFORMATION" is visible')
      cy.contains('b','Enter Account Information')
    cy.log('Step 6: Fill details: Title, Name, Email, Password, Date of birt')
      cy.get('#id_gender1').click()
      cy.get('[data-qa="password"]').type('testpassword')
      cy.get('[data-qa="days"]').select('30')
      cy.get('[data-qa="months"]').select('October')
      cy.get('[data-qa="years"]').select('1998')
    cy.log('Step 7: Select checkbox "Sign up for our newsletter!"')
      cy.get('#newsletter').click()
    cy.log('Step 8: Select checkbox "Receive special offers from our partners!"')
      cy.get('#optin').click()
    cy.log('Step 9: Fill details: First name, Last name, Company, Address, Address2, Country, State, City, Zipcode, Mobile Number')
      cy.get('[data-qa="first_name"]').type("First name")
      cy.get('[data-qa="last_name"]').type("Last name")
      cy.get('[data-qa="company"]').type("Company")
      cy.get('[data-qa="address"]').type("street addres")
      cy.get('[data-qa="country"]').select('Canada')
      cy.get('[data-qa="state"]').type('Ontario')
      cy.get('[data-qa="city"]').type('Toronto')
      cy.get('[data-qa="zipcode"]').type('M5V 3L9')
      cy.get('[data-qa="mobile_number"]').type('5516991509030')
    cy.log('Step 10: Click "Create Account button"')
      cy.get('[data-qa="create-account"]').click()
      cy.contains('b','Account Created!')
    cy.log('Step 11: Click "Continue" button')
      cy.get('[data-qa="continue-button"]').click()
    cy.log('Step 12: Verify that "Logged in as username" is visible')
      cy.contains('a','Logged in as')
    cy.log('Step 13: Click "Delete Account" button')
      cy.contains('a','Delete Account').click()
    cy.log('Step 14: Verify that "ACCOUNT DELETED!" is visible and click "Continue" button')
      cy.contains('b', 'Account Deleted!')
      cy.get('[data-qa="continue-button"]').click()
    })
})